config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:index, :show, :edit, :destroy, :new] do
    resources :participations, only: [:create, :new, :show]
  end

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "projects#index"

  get 'team', to: 'pages#team'
  get 'contact', to: 'pages#contact'
  get 'press', to:'pages#press'

  get "https" => "pages#https"

  mount Attachinary::Engine => "/attachinary"

  mount Facebook::Messenger::Server, at: 'bot'

  mount LetsencryptPlugin::Engine, at: '/'  # It must be at root level
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/financing.rb
class Financing < ApplicationRecord
  belongs_to :project
  belongs_to :partner
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :project
  belongs_to :user

  has_attachments :participation_pictures, maximum: 1

  def picture
    participation_pictures.first
  end
end

app/models/partner.rb
class Partner < ApplicationRecord
  has_many :financings
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :participations
  has_many :users, through: :participations
  has_many :financings

  def last_participations
    # project = Project.find(project_id)
    Participation.last(16).reverse
  end

  def user_count

  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :participations

    def self.find_for_messenger(facebook_id)
      user = User.find_by_facebook_id(facebook_id)
      unless user
        user = User.create(facebook_id: facebook_id)
        user.email = "fake_email_#{facebook_id}@facebook.com"
        user.password = Devise.friendly_token[0,20]
        user.save
      end
      user
    end

    def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # def configure_permitted_parameters
  #   # For additional fields in app/views/devise/registrations/new.html.erb
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  #   # For additional in app/views/devise/registrations/edit.html.erb
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
  end

  def team
  end

  def contact
  end

  def press
  end

  def htpps
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: [:edit, :update, :destroy]

  def new
    @participation = Participation.new
    @project = Project.find(params[:project_id])
  end

  def create
    @project = Project.find(params[:project_id])
    @participation = Participation.new(participation_params)
    @participation.project = @project
    # @participation.user = current_user

    if @participation.save
      redirect_to project_path(@project)
    else
      render :new
    end
    # respond_to do |format|
    #   if @participation.save
    #     format.html { redirect_to @participation, notice: 'Participation enregistrée' }
    #     format.json { render :show, status: :created, location: @participation }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @participation.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def edit
  end

  def update
    if @participation.update(participation_params)
        format.html { redirect_to @participation, notice: 'Participation mise à jour !' }
        format.json { render :show, status: :ok, location: @participation }
    else
      format.html { render :edit }
      format.json { render json: @participation.errors, status: :unprocessable_entity }
    end
  end

  def destroy
    @participation.destroy
    respond_to do |format|
      format.html { redirect_to participations_url, notice: 'Participation retirée.' }
      format.json { head :no_content }
    end
  end

  private

    def set_participation
      @participation = Participation.find(params[:id])
    end

    def participation_params
      params.require(:participation).permit(participation_pictures: [])
    end

    # def login
    #   if current_user == fimd dqtq
    #     # return :authenticate_user!
    #     return
    #   else
    #     new_user_registration_path
    #   end
    # end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    @current_project = Project.where(:current => true)[0]
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  @participations = Participation.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @participation = Participation.new
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :location, :pictures_goal, :project_picture)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/pages/https.html.erb
<iframe src="https://washin5.herokuapp.com/" />

app/views/participations/_form.html.erb
<div class="border">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-sm-offset-4">
          <div class="form-login">
          <%= simple_form_for([@project, @participation]) do |f| %>
          <%= f.input :participation_pictures, as: :attachinary, accept: "image" %>
          <div class="form-actions">
            <%= f.button :submit, class: "btn btn-card" %>
          </div>
        <% end %>
        </div>
      </div>
     </div>
    </div>
  </div>

app/views/participations/edit.html.erb
<h1>Mise à jour participation</h1>

<%= render 'form', participation: @participation %>

<%= link_to 'Show', @participation %> |
<%= link_to 'Back', participations_path %>

app/views/participations/index.html.erb
<!-- <div class="container">
  <div class="row">
    <p id="notice"><%= notice %></p>

    <% if !params[:q].blank? %>
      <h3><%= params[:q].upcase %> Participation</h3>
    <% else %>
      <h3>Vos participations</h3>
    <% end %>
  </div>
  <div class="row">
    <%= render '/shared/card_participation' %>

    <%= link_to 'Nouvelle participation', new_participation_path %>
  </div>
</div>
 -->

app/views/participations/new.html.erb
<%= render 'shared/banner' %>
<%= render 'form', participation: @participation, project: @project  %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="main">
  <%= render 'shared/banner' %>
  <div class="container">
    <div class="container">
    <div class="intro">
      <h1 class= "catch-phrase" > Envoyez vos selfies pour une bonne cause !</h1>
      <p >Savez-vous que, dans le monde, une personne sur dix n’a pas du tout d’accès à l’eau potable, alors qu'une douche de 9 min (durée moyenne en France) consomme près de 100 L d’eau potable ? <br >
        Avec le Wash in 5 Challenge, vous allez économiser l’eau pour la redistribuer là où elle manque.
      </p>
    </div>

      <!-- Projet en cours -->
      <h3 class="text-center title_project">Projet en cours</h3>
      <div class="row no-gutter">
        <div class="col-md-5">
          <div class="card shadow" style="background-image: url(<%= image_path 'filtre_WI5.jpg'%>);"> </div>
        </div>

        <div class="col-md-7">
          <div class="card-description shadow">
            <p class= "subtitle-card text-center">Mission <%= @current_project.name %></p>
            <div class="row">
              <div class="col-md-8">
                <p><%= @current_project.description %> de <%= @current_project.location %>. Installation d'un filtre à eau d'une contenance de 40 litres, transportable et facile à mettre en place.</p>
                <p class= "subtitle"> L'impact</p>
                <p>De l'eau potable au quotidien pour <%= @current_project.impact %> personnes</p>
              </div>

              <div class="col-md-4 text-center">
                <p>Financé par : <strong>Ma Rénov</strong></p>
                  <div class="image_resize" style="background-image: url(<%= image_path 'ma_renov_logo.jpg'%>);">
                  </div>
              </div>
            </div>

            <div class="row">
              <div class="goal col-md-12">
                <p class= "subtitle">Objectif : <%= @current_project.pictures_goal %> photos</p>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="<%=@current_project.pictures_goal%>" style="width:<%= @current_project.participations.count %>%;">
                    <span class="sr-only">40% Complete</span>
                  </div>
                </div>
                <p style="text-align: right">Il manque <%= @current_project.pictures_goal - @current_project.participations.count %> photos !</p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <%= link_to "Je soutiens ce projet", project_path(@current_project), class: "btn btn-card"%>
              </div>

              <div class="col-md-6 share">
                <div class="share">
                  <a href="http://www.facebook.com/sharer.php?u=<%= project_path(@current_project) %>" target="_blank" class="bg-facebook">
                    <i class="fa fa-facebook fa-share-card"></i>
                  </a>
                  <a href="https://twitter.com/washin5challeng" target="_blank" class="bg-twitter">
                    <i class="fa fa-twitter fa-share-card"></i>
                  </a>
                  <a href="https://www.instagram.com/washin5challenge" target="_blank" class="bg-instagram">
                    <i class="fa fa-instagram fa-share-card"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


    </div>

    <!-- Projet à venir -->
    <div class="container">
      <h3 class="text-center title_project">Projets à venir</h3>
      <% @projects.first(3).each do |project| %>
      <div class="project_card col-md-4 col-xs-12">
          <!-- insert <div class="card"> -->
        <div class="img_card_project shadow" alt= "project distribution eau inde card" style="background-image:url(<%= image_path project.project_picture %>)";>
        </div>
         <!--  <%= image_tag project.project_picture %> -->
          <div class= "card_block shadow">
            <div class="card_title text-center">
              <h3> <%= project.name %></h3>
            </div>
            <div class="row">
              <div class="col-xs-6 text-center">
                <p>Objectif : <br /> <%= project.pictures_goal %> photos</p>
              </div>
              <div class="col-xs-6 text-center">
                <p>Financé par : <br /> <strong>CJD Montpellier</strong></p>
              </div>
            </div>
            <p><%= project.description %></p>
            <p class= "subtitle">Impact :</p><p> <%= project.impact %> personnes</p>
          </div>
      </div>
      <% end %>
    </div>

    <!-- Projet réalisés -->

    <div class="container">
      <h3 class="text-center title_project">Projets réalisés</h3>
      <div class="row">
        <div class="project_card col-md-3 col-xs-12">
          <div class="img_card_project_done shadow" alt= "project distribution eau inde card" style="background-image:url(<%= image_path 'robinets.jpg' %>)";>
          </div>

          <div class= "card_block shadow">
            <div class="card_title text-center">
              <h3>Filtre à eau</h3>
            </div>
            <div class="row no-gutter">
              <div class="col-xs-6 text-center">
                <p>Objectif : <br /> 125 photos</p>
              </div>
              <div class="col-xs-6 text-center">
                <p>Financé par :<br />  <strong>Réaxion</strong></p>
              </div>
              <p class= "subtitle">Impact :</p><p>  30 personnes</p>
            </div>
          </div>
        </div>
        <!--projet 2-->
        <div class="project_card col-md-3 col-xs-12">
          <div class="img_card_project_done shadow" alt= "project distribution eau inde card" style="background-image:url(<%= image_path 'forage_femmes.jpg' %>)";>
          </div>
          <div class= "card_block shadow">
            <div class="card_title text-center">
              <h3>Filtre à eau</h3>
            </div>
            <div class="row no-gutter">
              <div class="col-xs-6 text-center">
                <p>Objectif : <br /> 125 photos</p>
              </div>
              <div class="col-xs-6 text-center">
                <p>Financé par : <br /><strong>Cabinet d'avocats Frances Dehors</strong></p>
              </div>
              <p class= "subtitle">Impact :</p><p>  30 personnes</p>
            </div>
          </div>
        </div>

        <!--projet 3-->
        <div class="project_card col-md-3 col-xs-12">
          <div class="img_card_project_done shadow" alt= "project distribution eau inde card" style="background-image:url(<%= image_path 'pompe_eau_femmes.jpg' %>)";>
          </div>
          <div class= "card_block shadow">
            <div class="card_title text-center">
              <h3>Filtre à eau</h3>
            </div>
            <div class="row no-gutter">
              <div class="col-xs-6 text-center">
                <p>Objectif : <br /> 125 photos</p>
              </div>
              <div class="col-xs-6 text-center">
                <p>Financé par :<br />  <strong>CJD France</strong></p>
              </div>
              <p class= "subtitle">Impact :</p><p>  30 personnes</p>
            </div>
          </div>
        </div>

        <!--Projet 4-->
        <div class="project_card col-md-3 col-xs-12">
          <div class="img_card_project_done shadow" alt= "project distribution eau inde card" style="background-image:url(<%= image_path 'reservoir.jpg' %>)";>
          </div>
          <div class= "card_block shadow">
            <div class="card_title text-center">
              <h3>Filtre à eau</h3>
            </div>
            <div class="row no-gutter">
              <div class="col-xs-6 text-center">
                <p>Objectif : <br /> 125 photos</p>
              </div>
              <div class="col-xs-6 text-center">
                <p>Financé par :<br />  <strong>Ma Rénov'</strong></p>
              </div>
              <p class= "subtitle">Impact :</p><p>  30 personnes</p>
            </div>
          </div>
        </div>
      </div>
    </div>



    <!-- Follow us -->

        <div class="mosaique" style="background-image: url(<%= image_path 'mosaique.jpg' %>);">
          <div class="follow_us text-center">
            <h4>Rejoignez-nous</h4>
            <a href="https://www.facebook.com/washin5challenge/?fref=ts" target="_blank">
              <i class="fa fa-facebook fa-share-card-white"> </i>
            </a>
            <a href="https://twitter.com/washin5challeng" target="_blank">
              <i class="fa fa-twitter fa-share-card-white"> </i>
            </a>
            <a href="https://www.instagram.com/washin5challenge" target="_blank">
              <i class="fa fa-instagram fa-share-card-white "> </i>
            </a>
            <div class="">
              <%= link_to "Photo Live", new_project_participation_path(@current_project), class: "btn btn-photolive"%>
            </div>
          </div>
        </div>
    </div>
  </div>

</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/shared/_card_participation.html.erb
<div class="container">
  <div class="row">
    <% @participations.each do |participation| %>
      <div class="col-xs-6 col-md-3 ">
        <div class="participation-card">
          <div class="footer-picture">
            <% if participation.picture_participation? %>
              <%= link_to participation_path(participation) do %>
                <%= cl_image_tag participation.participation_picture.path, width: 300, height: 300, crop: :fill %>
                <% end %>
            <% end %>
<!--              <% if current_user == participation.user_id %>
            <%= link_to(raw("<i class='fa fa-pencil-square-o' aria-hidden='true'></i>"), edit_participation_path(participation)) %>

            <%= link_to(raw("<i class='fa fa-trash-o' aria-hidden='true'></i>"), participation, method: :delete, data: { confirm: 'Vous êtes sûr ?' }) %>
          <% end %> -->
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
<div class="container">
    <div class="row">
    <div class="col-md-12">
      <div id="Carousel" class="carousel slide">

      <!-- Carousel items -->
      <div class="carousel-inner">

      <div class="item active">
        <div class="row">
          <div class="col-md-3"><%= link_to((image_tag"cleaning-bio.png"), 'http://www.cleaning-bio34.fr/', class: 'img-part') %></div>
          <div class="col-md-3"><%= link_to((image_tag"cjd-montpelier.png"), 'https://cjd-montpellier.net/', class: 'img-part') %></div>
           <div class="col-md-3"><%= link_to((image_tag"3wanted-eb.png"), 'http://www.wantedweb.fr/', class: 'img-part') %></div>
            <div class="col-md-3"><%= link_to((image_tag"drole-de-pain.png"), 'http://www.droledepain.fr/', class: 'img-part') %></div>
        </div><!--.row-->
      </div><!--.item-->

      <div class="item">
        <div class="row">
          <div class="col-md-3"><%= link_to((image_tag"cleaning-bio.png"), 'http://www.cleaning-bio34.fr/', class: 'img-part') %></div>
          <div class="col-md-3"><%= link_to((image_tag"cjd-montpelier.png"), 'https://cjd-montpellier.net/', class: 'img-part') %></div>
           <div class="col-md-3"><%= link_to((image_tag"3wanted-eb.png"), 'http://www.wantedweb.fr/', class: 'img-part') %></div>
            <div class="col-md-3"><%= link_to((image_tag"drole-de-pain.png"), 'http://www.droledepain.fr/', class: 'img-part') %></div>
        </div><!--.row-->
      </div><!--.item-->

      <div class="item">
        <div class="row">
          <div class="col-md-3"><%= link_to((image_tag"cleaning-bio.png"), 'http://www.cleaning-bio34.fr/', class: 'img-part') %></div>
          <div class="col-md-3"><%= link_to((image_tag"cjd-montpelier.png"), 'https://cjd-montpellier.net/', class: 'img-part') %></div>
           <div class="col-md-3"><%= link_to((image_tag"3wanted-eb.png"), 'http://www.wantedweb.fr/', class: 'img-part') %></div>
            <div class="col-md-3"><%= link_to((image_tag"drole-de-pain.png"), 'http://www.droledepain.fr/', class: 'img-part') %></div>
        </div><!--.row-->
      </div><!--.item-->

      </div><!--.carousel-inner-->
        <a data-slide="prev" href="#Carousel" class="left carousel-control">‹</a>
        <a data-slide="next" href="#Carousel" class="right carousel-control">›</a>
      </div><!--.Carousel-->

    </div>
  </div>
</div><!--.container-->
  <!-- <div class="img-part">
    <ul class="img-list">

      <li id="footer-cleaning-bio">
      <%= link_to((image_tag"cleaning-bio.png"), 'http://www.cleaning-bio34.fr/') %>
      </li>

      <li>
      <%= link_to((image_tag"cjd-montpelier.png"), 'https://cjd-montpellier.net/') %>
      </li>

      <li>
      <%= link_to((image_tag"3wanted-eb.png"), 'http://www.wantedweb.fr/') %>
      </li>

      <li id="footer-drole-de-pain">
      <%= link_to((image_tag"drole-de-pain.png"), 'http://www.droledepain.fr/') %>
      </li>

    </ul>
  </div> -->
  <div class="footer_link">
    <div class="container">
      <div class="row">
        <div class="mentions-footer">
          <div class="col-xs-6 col-sm-4">
            <ul>
              <li class="link-list"><%= link_to "Projets", contact_path %></li>
              <li class="link-list"><%= link_to "Photo",  contact_path%></li>
              <li class="link-list"><%= link_to "Presse", press_path %></li>
            </ul>
         </div>

          <div class="col-xs-6 col-sm-4">
            <ul>
              <li class="link-list"><%= link_to "Partenaires", contact_path %></li>
              <li class="link-list"><%= link_to "Equipe", team_path %></li>
              <li class="link-list"><%= link_to "Contact", contact_path %></li>
            </ul>
          </div>

          <div class="col-xs-6 col-sm-4">
            <ul >
              <li class="link-list"><%= link_to "Mentions légales", contact_path %></li>
              <li class="link-list"> <%= link_to "Politique de confidentialité", contact_path %></li>
              <li class="link-list"><%= link_to "Conditions d'utilisation", contact_path %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

<!--<footer><footer class="row" style="background-color:red; padding:bottom;">
  <div class="col-md-6" style="background-color:blue;">
    <h3>hhhhhhhhh</h3>
  </div>
  <div class="col-md-6" style="background-color:red;">
    <h3>hhhhhhhhh</h3>
  </div>

</footer>-->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png" , size: "50"%>
  <% end %>

  <div class="navbar-wagon-right">
    <div class="navbar-share">
      <a href="https://www.facebook.com/washin5challenge/?fref=ts" target="_blank" class="bg-facebook">
        <i class="fa fa-facebook fa-share-navbar"></i>
      </a>
      <a href="https://twitter.com/washin5challeng" target="_blank" class="bg-twitter">
        <i class="fa fa-twitter fa-share-navbar"></i>
      </a>
      <a href="https://www.instagram.com/washin5challenge" target="_blank" class="bg-instagram">
        <i class="fa fa-instagram fa-share-navbar"></i>
      </a>
    </div>
    <span class="slash hidden-xs hidden-sm"></span>

    <div class="hidden-xs hidden-sm">
      <ul class="nav nav-pills">
        <li role="presentation"><a href="#">Projets</a></li>
        <li role="presentation"><a href="#">Photos</a></li>
        <li role="presentation"><%= link_to "Presse", press_path %></li>
        <li role="presentation"><%= link_to "Equipe", team_path %></li>
        <li role="presentation"><%= link_to "Contact", contact_path %></li>
        <li role="presentation"><%= link_to "Partenaires", contact_path %></li>
      </ul>
    </div>

      <!-- Different navigation if login or not -->
     <!--  <% if user_signed_in? %>
      <!-- Profile picture and dropdown -->
      <!-- <div class="navbar-wagon-item"> -->
       <!--  <div class="dropdown">
          <%= image_tag "user_connected.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Mon profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Déconnexion") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div> -->

      <!-- <% else %> -->
<!--
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "user_disconnected.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            <!-- Login text link -->
           <!--  <li>
              <%= link_to t(".sign_in", default: "S'inscrire"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
          </ul>
        </div> -->
  <!--     </div> -->
      <!-- <% end %> -->
  </div>

        <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-right hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li role="presentation"><a href="#">Projets</a></li>
          <li role="presentation"><a href="#">Photos</a></li>
          <li role="presentation"><a href="#">Presse</a></li>
          <li role="presentation"><a href="#">Equipe</a></li>
          <li role="presentation"><a href="#">Contact</a></li>

         <!--  <% if user_signed_in? %>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
              <i class="fa fa-pencil"></i> <%= t(".edit-profile", default: "Modifier votre profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Déconnexion") %>
              <% end %>
            </li>

          <% else %>

            <li>
              <%= link_to t(".sign_up", default: "S'inscrire"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
            <li>
              <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
            </li>

          <% end %> -->
        </ul>
      </div>
    </div>
  </div>
</div>